"""Add UserChapter model and update relationships

Revision ID: 20a93d21271f
Revises: ba9f56ce18a4
Create Date: 2025-02-18 13:51:37.495974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a93d21271f'
down_revision = 'ba9f56ce18a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chapter_id', sa.Integer(), nullable=True),
    sa.Column('coverage', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('prev_year_questions', sa.String(length=64), nullable=True),
    sa.Column('revisions', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_constraint('chapter_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('status')
        batch_op.drop_column('prev_year_questions')
        batch_op.drop_column('coverage')
        batch_op.drop_column('revisions')

    with op.batch_alter_table('mock_test', schema=None) as batch_op:
        batch_op.drop_index('ix_mock_test_name')
        batch_op.create_index(batch_op.f('ix_mock_test_name'), ['name'], unique=False)

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint('subject_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('subject_user_id_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('mock_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mock_test_name'))
        batch_op.create_index('ix_mock_test_name', ['name'], unique=True)

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revisions', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('coverage', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('prev_year_questions', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('chapter_user_id_fkey', 'user', ['user_id'], ['id'])

    op.drop_table('user_chapter')
    # ### end Alembic commands ###
