"""Add coverage, status, prev_year_questions, and revisions fields

Revision ID: 3352f1ef058a
Revises: 
Create Date: 2025-02-09 17:41:34.502863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3352f1ef058a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coverage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('prev_year_questions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('revisions', sa.Integer(), nullable=True))

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coverage', sa.Float(), nullable=True))

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_column('coverage')

    with op.batch_alter_table('chapter', schema=None) as batch_op:
        batch_op.drop_column('revisions')
        batch_op.drop_column('prev_year_questions')
        batch_op.drop_column('status')
        batch_op.drop_column('coverage')

    # ### end Alembic commands ###
