"""Add mock_test table

Revision ID: cae0b264b3a3
Revises: e32da4cd9245
Create Date: 2025-02-11 11:09:43.182030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cae0b264b3a3'
down_revision = 'e32da4cd9245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('total_marks', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mock_test', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mock_test_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_test', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mock_test_name'))

    op.drop_table('mock_test')
    # ### end Alembic commands ###
